export const ON_INPUT_CHANGE = 'ON_INPUT_CHANGE';
export const GET_ALL_TASKS = 'GET_ALL_TASKS';
export const CREATE_TASK = 'CREATE_TASK';
export const COMPLETE_TASK = 'COMPLETE_TASK';
export const EDIT_MODE = 'EDIT_MODE';
export const SAVE_EDITED_TASK = 'SAVE_EDITED_TASK';
export const CANCEL_EDIT_MODE = 'CANCEL_EDIT_MODE';
